server:
  port: 8080

spring:
  zipkin:
    baseUrl : http://localhost:9411/zipkin/
  application:
    name: yellowTask
  sql:
    init: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/offers
    username: admin
    password: Qwertz123
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

#Optional redis as db properties
redis.asDb.hostname: localhost
redis.asDb.port: 6380

#Optional mongo as db properties
mongo.asDb.hostname: localhost
mongo.asDb.port: 27017
mongo.asDb.databaseName: offers
mongo.enabled: false
